/* Autogenerated by png2wx.pl on Tue Feb 21 15:00:34 2017 */
#ifndef ICONSH
#define ICONSH 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_oplaydo1;
extern wxBitmap *_img_oplaydo1_pi;

#endif /* ICONS.H */
